// ************************************************************************
// Generated by scripts/lib/meter-detail.mjs. Don't hand-edit.
// upstream:check rejects a hand edit. upstream:prune overwrites this file.
// ************************************************************************

export type MeterDetail = {
  primary?: true | "kiroCredits" | "poeBalance";
  secondary?: true;
  primaryReset?: true;
};

export const METER_DETAIL: Record<string, MeterDetail> = {
  alibaba: { primary: true, secondary: true },
  copilot: { primary: true },
  kilo: { primary: true, secondary: true },
  kiro: { primary: "kiroCredits" },
  warp: { primary: true, secondary: true },
  openrouter: { primaryReset: true },
  alibabatokenplan: { primary: true, secondary: true },
  manus: { primary: true, secondary: true },
  mimo: { primary: true },
  mistral: { primary: true },
  deepseek: { primary: true },
  deepinfra: { primary: true },
  qoder: { primary: true },
  litellm: { primary: true, secondary: true },
  poe: { primary: "poeBalance" },
  chutes: { primary: true, secondary: true },
  neuralwatt: { primary: true },
  longcat: { primary: true, secondary: true },
  zenmux: { primary: true },
  aixy: { primary: true, secondary: true },
  bifrost: { primary: true, secondary: true },
  helmcode: { primary: true },
  llmman: { primary: true },
  raycast: { primary: true },
};
