import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  METER_DETAIL_BANNER,
  checkMeterDetailFile,
  menuCardReviewProblems,
  MENU_CARD_WATCH_PATHS,
  meterEntryFromPresentation,
  parseMenuCardPresentation,
  renderMeterDetail,
} from "./meter-detail.mjs";

const EMPTY = {
  showsPrimaryBalanceDescription: false,
  showsSecondaryBalanceDescription: false,
  hidesPrimaryResetWithoutDate: false,
  clearsPrimaryReset: false,
  primaryDescriptionPlacement: "standard",
  primaryDetailKind: "none",
  usageNotesResolver: null,
  extraRateWindowUsesResetDescriptionAsDetail: null,
  extraResetDescriptionAsDetail: null,
  primaryDescriptionIsDetail: null,
};

describe("meter detail generation", () => {
  it("keeps the do-not-edit banner on every generated table", () => {
    const lines = METER_DETAIL_BANNER.split("\n");
    expect(lines[0]).toMatch(/^\/\/ \*+$/);
    expect(lines[1]).toBe("// Generated by scripts/lib/meter-detail.mjs. Don't hand-edit.");
    expect(lines[2]).toBe("// upstream:check rejects a hand edit. upstream:prune overwrites this file.");
    expect(lines[3]).toBe(lines[0]);
    expect(lines[4]).toBe("");
    expect(lines[0].length).toBeGreaterThanOrEqual(lines[2].length);
    expect(renderMeterDetail({}).startsWith(METER_DETAIL_BANNER)).toBe(true);
  });

  it("ignores comments inside a menu card call", () => {
    const source = `
      ProviderMenuCardPresentation(
        supportsInlineTokenCostDashboard: true,
        // Antigravity has no single account-wide weekly quota: it reports a weekly bucket
        // per model family, and \`semanticWindows\` surfaces whichever family is most
        // constrained, while the cost bucketed into it spans every model.
        showsPrimaryBalanceDescription: false)
    `;
    const parsed = parseMenuCardPresentation(source, "Antigravity.swift");
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.presentation.showsPrimaryBalanceDescription).toBe(false);
    expect(meterEntryFromPresentation("antigravity", parsed.presentation)).toBeUndefined();
  });

  it("rejects two menu card calls and treats zero calls as defaults", () => {
    const none = parseMenuCardPresentation("struct Empty {}", "Empty.swift");
    expect(none.ok).toBe(true);
    const doubled = parseMenuCardPresentation(
      "ProviderMenuCardPresentation()\nProviderMenuCardPresentation()",
      "Double.swift",
    );
    expect(doubled.ok).toBe(false);
    if (doubled.ok) return;
    expect(doubled.error).toMatch(/2 ProviderMenuCardPresentation calls/);
  });

  it("maps placements, balance flags, detail kinds, and the forced menu-card rows", () => {
    expect(meterEntryFromPresentation("devin", EMPTY)).toBeUndefined();
    expect(meterEntryFromPresentation("warp", EMPTY)).toEqual({ secondaryDetailText: true });
    expect(meterEntryFromPresentation("alibaba", EMPTY)).toEqual({
      secondaryDetailText: true,
      tertiaryDetailText: true,
    });
    expect(meterEntryFromPresentation("alibabatokenplan", EMPTY)).toEqual({
      secondaryDetailText: true,
      tertiaryDetailText: true,
    });
    expect(meterEntryFromPresentation("plain", { ...EMPTY, primaryDescriptionPlacement: "standard" })).toBeUndefined();
    expect(meterEntryFromPresentation("copilot", { ...EMPTY, primaryDescriptionPlacement: "detailLeft" })).toEqual({
      primaryDescriptionPlacement: "detailLeft",
      secondaryReplacesPace: "resetDescription",
    });
    expect(meterEntryFromPresentation("zenmux", { ...EMPTY, primaryDescriptionPlacement: "detail" })).toEqual({
      primaryDescriptionPlacement: "detail",
      secondaryReplacesPace: "resetDescription",
      secondaryHidesResetWithoutDate: true,
    });
    expect(meterEntryFromPresentation("openrouter", { ...EMPTY, primaryDescriptionPlacement: "reset" })).toEqual({
      primaryDescriptionPlacement: "reset",
    });
    expect(meterEntryFromPresentation("kiro", { ...EMPTY, primaryDetailKind: "kiroCredits" })).toEqual({
      primaryDetailKind: "kiroCredits",
      secondaryReplacesPace: "kiroBonusCredits",
      extraDetailLeft: "kiroOverage",
    });
    expect(meterEntryFromPresentation("poe", { ...EMPTY, primaryDetailKind: "poeBalance" })).toEqual({
      primaryDetailKind: "poeBalance",
    });
    expect(meterEntryFromPresentation("cursor", { ...EMPTY, primaryDetailKind: "requestQuota" })).toBeUndefined();
    expect(
      meterEntryFromPresentation("raycast", {
        ...EMPTY,
        showsPrimaryBalanceDescription: true,
        hidesPrimaryResetWithoutDate: true,
      }),
    ).toEqual({
      showsPrimaryBalanceDescription: true,
      hidesPrimaryResetWithoutDate: true,
    });
    expect(
      meterEntryFromPresentation("manus", {
        ...EMPTY,
        showsSecondaryBalanceDescription: true,
        clearsPrimaryReset: true,
      }),
    ).toEqual({
      showsSecondaryBalanceDescription: true,
      clearsPrimaryReset: true,
    });
    expect(meterEntryFromPresentation("sub2api", { ...EMPTY, extraResetDescriptionAsDetail: true })).toEqual({
      extraResetDescriptionAsDetail: true,
    });
    expect(
      meterEntryFromPresentation("mistral", { ...EMPTY, extraResetDescriptionAsDetail: "mistral-monthly-plan" }),
    ).toEqual({ extraResetDescriptionAsDetail: "mistral-monthly-plan" });
  });

  it("ports a true extra-window closure and an id check, and leaves any other body unportable", () => {
    const all = parseMenuCardPresentation(
      "ProviderMenuCardPresentation(extraRateWindowUsesResetDescriptionAsDetail: { _ in true })",
      "Sub2API.swift",
    );
    expect(all.ok).toBe(true);
    if (!all.ok) return;
    expect(all.presentation.extraResetDescriptionAsDetail).toBe(true);
    expect(all.presentation.extraRateWindowUsesResetDescriptionAsDetail).toBeNull();

    const id = parseMenuCardPresentation(
      'ProviderMenuCardPresentation(extraRateWindowUsesResetDescriptionAsDetail: { $0.id == "mistral-monthly-plan" })',
      "Mistral.swift",
    );
    expect(id.ok).toBe(true);
    if (!id.ok) return;
    expect(id.presentation.extraResetDescriptionAsDetail).toBe("mistral-monthly-plan");
    expect(id.presentation.extraRateWindowUsesResetDescriptionAsDetail).toBeNull();

    const other = parseMenuCardPresentation(
      'ProviderMenuCardPresentation(extraRateWindowUsesResetDescriptionAsDetail: { name in name.id.hasPrefix("x") })',
      "Other.swift",
    );
    expect(other.ok).toBe(true);
    if (!other.ok) return;
    expect(other.presentation.extraResetDescriptionAsDetail).toBeNull();
    expect(other.presentation.extraRateWindowUsesResetDescriptionAsDetail).toContain("hasPrefix");
  });

  it("rejects a hand edit and accepts the regenerated file", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "meter-detail-"));
    const entries = { raycast: { showsPrimaryBalanceDescription: true } };
    const file = path.join(root, "src/providers/meterDetail.ts");
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(
      file,
      renderMeterDetail(entries).replace(
        "showsPrimaryBalanceDescription: true",
        "showsPrimaryBalanceDescription: true /* edited */",
      ),
    );
    await expect(checkMeterDetailFile(root, entries)).resolves.toEqual([
      "src/providers/meterDetail.ts does not match the menu card descriptors. Regenerate it.",
    ]);
    await writeFile(file, renderMeterDetail(entries));
    await expect(checkMeterDetailFile(root, entries)).resolves.toEqual([]);
    await rm(root, { recursive: true, force: true });
  });

  it("names a changed plugin file until the review lists it at the candidate", () => {
    const candidate = "b".repeat(40);
    const plugin = "Sources/CodexBarCore/Resources/Plugins/raycast.js";
    const changed = [plugin, "README.md"];
    const missingSha = menuCardReviewProblems(
      { sha: "a".repeat(40), paths: [...MENU_CARD_WATCH_PATHS] },
      candidate,
      changed,
    );
    const missingText = missingSha.join("\n");
    expect(missingText).toContain("raycast.js");
    expect(missingText).toContain(candidate);
    expect(missingText).not.toContain("README.md");

    const shaOnly = menuCardReviewProblems({ sha: candidate, paths: [...MENU_CARD_WATCH_PATHS] }, candidate, changed);
    expect(shaOnly.join("\n")).toContain("raycast.js");
    expect(
      menuCardReviewProblems({ sha: candidate, paths: [...MENU_CARD_WATCH_PATHS, plugin] }, candidate, changed),
    ).toEqual([]);
  });
});
