import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  METER_DETAIL_BANNER,
  checkMeterDetailFile,
  menuCardReviewProblems,
  MENU_CARD_WATCH_PATHS,
  meterEntryFromPresentation,
  parseMenuCardPresentation,
  renderMeterDetail,
} from "./meter-detail.mjs";

const EMPTY = {
  showsPrimaryBalanceDescription: false,
  showsSecondaryBalanceDescription: false,
  primaryDescriptionPlacement: "standard",
  primaryDetailKind: "none",
  usageNotesResolver: null,
  extraRateWindowUsesResetDescriptionAsDetail: null,
  primaryDescriptionIsDetail: null,
};

describe("meter detail generation", () => {
  it("keeps the do-not-edit banner on every generated table", () => {
    const lines = METER_DETAIL_BANNER.split("\n");
    expect(lines[0]).toMatch(/^\/\/ \*+$/);
    expect(lines[1]).toBe("// Generated by scripts/lib/meter-detail.mjs. Don't hand-edit.");
    expect(lines[2]).toBe("// upstream:check rejects a hand edit. upstream:prune overwrites this file.");
    expect(lines[3]).toBe(lines[0]);
    expect(lines[4]).toBe("");
    expect(lines[0].length).toBeGreaterThanOrEqual(lines[2].length);
    expect(renderMeterDetail({}).startsWith(METER_DETAIL_BANNER)).toBe(true);
  });

  it("ignores comments inside a menu card call", () => {
    const source = `
      ProviderMenuCardPresentation(
        supportsInlineTokenCostDashboard: true,
        // Antigravity has no single account-wide weekly quota: it reports a weekly bucket
        // per model family, and \`semanticWindows\` surfaces whichever family is most
        // constrained, while the cost bucketed into it spans every model.
        showsPrimaryBalanceDescription: false)
    `;
    const parsed = parseMenuCardPresentation(source, "Antigravity.swift");
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.presentation.showsPrimaryBalanceDescription).toBe(false);
    expect(meterEntryFromPresentation("antigravity", parsed.presentation)).toBeUndefined();
  });

  it("rejects two menu card calls and treats zero calls as defaults", () => {
    const none = parseMenuCardPresentation("struct Empty {}", "Empty.swift");
    expect(none.ok).toBe(true);
    const doubled = parseMenuCardPresentation(
      "ProviderMenuCardPresentation()\nProviderMenuCardPresentation()",
      "Double.swift",
    );
    expect(doubled.ok).toBe(false);
    if (doubled.ok) return;
    expect(doubled.error).toMatch(/2 ProviderMenuCardPresentation calls/);
  });

  it("maps balance flags, placements, and the forced secondary rows", () => {
    expect(meterEntryFromPresentation("devin", EMPTY)).toBeUndefined();
    expect(meterEntryFromPresentation("warp", EMPTY)).toEqual({ secondary: true });
    expect(meterEntryFromPresentation("alibaba", EMPTY)).toEqual({ secondary: true });
    expect(meterEntryFromPresentation("alibabatokenplan", EMPTY)).toEqual({ secondary: true });
    expect(
      meterEntryFromPresentation("copilot", { ...EMPTY, primaryDescriptionPlacement: "detailLeft" }),
    ).toEqual({ primary: true });
    expect(meterEntryFromPresentation("zenmux", { ...EMPTY, primaryDescriptionPlacement: "detail" })).toEqual({
      primary: true,
    });
    expect(meterEntryFromPresentation("openrouter", { ...EMPTY, primaryDescriptionPlacement: "reset" })).toEqual({
      primaryReset: true,
    });
    expect(meterEntryFromPresentation("kiro", { ...EMPTY, primaryDetailKind: "kiroCredits" })).toEqual({
      primary: "kiroCredits",
    });
    expect(meterEntryFromPresentation("poe", { ...EMPTY, primaryDetailKind: "poeBalance" })).toEqual({
      primary: "poeBalance",
    });
    expect(meterEntryFromPresentation("cursor", { ...EMPTY, primaryDetailKind: "requestQuota" })).toBeUndefined();
    expect(meterEntryFromPresentation("raycast", { ...EMPTY, showsPrimaryBalanceDescription: true })).toEqual({
      primary: true,
    });
  });

  it("rejects a hand edit and accepts the regenerated file", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "meter-detail-"));
    const entries = { raycast: { primary: true } };
    const file = path.join(root, "src/providers/meterDetail.ts");
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, renderMeterDetail(entries).replace("primary: true", "primary: true /* edited */"));
    await expect(checkMeterDetailFile(root, entries)).resolves.toEqual([
      "src/providers/meterDetail.ts does not match the menu card descriptors. Regenerate it.",
    ]);
    await writeFile(file, renderMeterDetail(entries));
    await expect(checkMeterDetailFile(root, entries)).resolves.toEqual([]);
    await rm(root, { recursive: true, force: true });
  });

  it("names a changed plugin file until the review lists it at the candidate", () => {
    const candidate = "b".repeat(40);
    const plugin = "Sources/CodexBarCore/Resources/Plugins/raycast.js";
    const changed = [plugin, "README.md"];
    const missingSha = menuCardReviewProblems(
      { sha: "a".repeat(40), paths: [...MENU_CARD_WATCH_PATHS] },
      candidate,
      changed,
    );
    const missingText = missingSha.join("\n");
    expect(missingText).toContain("raycast.js");
    expect(missingText).toContain(candidate);
    expect(missingText).not.toContain("README.md");

    const shaOnly = menuCardReviewProblems({ sha: candidate, paths: [...MENU_CARD_WATCH_PATHS] }, candidate, changed);
    expect(shaOnly.join("\n")).toContain("raycast.js");
    expect(
      menuCardReviewProblems({ sha: candidate, paths: [...MENU_CARD_WATCH_PATHS, plugin] }, candidate, changed),
    ).toEqual([]);
  });
});
