// Generates src/providers/meterDetail.ts from menu-card descriptor literals.
// upstream:check rejects a hand edit. upstream:prune rewrites the file.

import { readFile } from "node:fs/promises";
import path from "node:path";
import { CATALOG_PROVIDER_ORDER } from "./provider-modules.mjs";

export const METER_DETAIL_PATH = "src/providers/meterDetail.ts";

// secondaryMetric copies resetDescription for these ids without the descriptor flag.
export const FORCED_SECONDARY_BALANCE = new Set(["alibaba", "alibabatokenplan", "warp"]);

export const MENU_CARD_WATCH_PATHS = [
  "Sources/CodexBar/MenuCardView.swift",
  "Sources/CodexBar/MenuCardView+ModelHelpers.swift",
  "Sources/CodexBar/MenuCardMetricRow.swift",
  "Sources/CodexBarCLI/CLIRenderer.swift",
  "Sources/CodexBarCore/Resources/Plugins/",
];

const METER_DETAIL_DO_NOT_EDIT = [
  "// Generated by scripts/lib/meter-detail.mjs. Don't hand-edit.",
  "// upstream:check rejects a hand edit. upstream:prune overwrites this file.",
];
const METER_DETAIL_RULE = `// ${"*".repeat(Math.max(...METER_DETAIL_DO_NOT_EDIT.map((line) => line.length)) - 3)}`;

export const METER_DETAIL_BANNER = `${[METER_DETAIL_RULE, ...METER_DETAIL_DO_NOT_EDIT, METER_DETAIL_RULE].join("\n")}\n\n`;

const PLACEMENTS = new Set(["standard", "reset", "detail", "detailLeft"]);
const DETAIL_KINDS = new Set(["none", "poeBalance", "kiroCredits", "requestQuota"]);
const TRIVIAL_FALSE = "{_infalse}";
const TRIVIAL_UNHANDLED = "{_in.unhandled}";

const CLOSURE_FIELDS = [
  ["usageNotesResolver", "usageNotesResolver"],
  ["extraRateWindowUsesResetDescriptionAsDetail", "extraRateWindowUsesResetDescriptionAsDetail"],
  ["primaryDescriptionIsDetail", "primaryDescriptionIsDetail"],
];

export function parseMenuCardPresentation(source, filePath = "descriptor") {
  try {
    const cardCalls = findCalls(source, "ProviderMenuCardPresentation");
    const menuCalls = findCalls(source, "ProviderMenuDescriptorPresentation");
    if (cardCalls.length > 1) {
      throw new Error(`${cardCalls.length} ProviderMenuCardPresentation calls`);
    }
    if (menuCalls.length > 1) {
      throw new Error(`${menuCalls.length} ProviderMenuDescriptorPresentation calls`);
    }
    const card = cardCalls.length === 0 ? new Map() : parseArgs(cardCalls[0]);
    const menu = menuCalls.length === 0 ? new Map() : parseArgs(menuCalls[0]);
    return {
      ok: true,
      presentation: {
        showsPrimaryBalanceDescription: boolArg(card, "showsPrimaryBalanceDescription", false),
        showsSecondaryBalanceDescription: boolArg(card, "showsSecondaryBalanceDescription", false),
        primaryDescriptionPlacement: enumArg(card, "primaryDescriptionPlacement", "standard", PLACEMENTS),
        primaryDetailKind: enumArg(card, "primaryDetailKind", "none", DETAIL_KINDS),
        usageNotesResolver: closureArg(card, "usageNotesResolver", TRIVIAL_UNHANDLED),
        extraRateWindowUsesResetDescriptionAsDetail: closureArg(
          card,
          "extraRateWindowUsesResetDescriptionAsDetail",
          TRIVIAL_FALSE,
        ),
        primaryDescriptionIsDetail: closureArg(menu, "primaryDescriptionIsDetail", TRIVIAL_FALSE),
      },
    };
  } catch (error) {
    return { ok: false, error: `${filePath}: ${error instanceof Error ? error.message : error}` };
  }
}

export function meterEntryFromPresentation(id, presentation) {
  const entry = {};
  const placement = presentation.primaryDescriptionPlacement;
  const kind = presentation.primaryDetailKind;
  if (kind === "kiroCredits" || kind === "poeBalance") {
    entry.primary = kind;
  } else if (
    presentation.showsPrimaryBalanceDescription ||
    placement === "detail" ||
    placement === "detailLeft"
  ) {
    entry.primary = true;
  }
  if (placement === "reset") {
    entry.primaryReset = true;
  }
  if (presentation.showsSecondaryBalanceDescription || FORCED_SECONDARY_BALANCE.has(id)) {
    entry.secondary = true;
  }
  return Object.keys(entry).length === 0 ? undefined : entry;
}

export function compareMeterDetail(presentations, table) {
  const problems = [];
  const entries = {};
  for (const [id, presentation] of presentations) {
    const expected = meterEntryFromPresentation(id, presentation);
    if (expected) entries[id] = expected;
    const actual = table[id];
    if (!sameEntry(expected, actual)) {
      problems.push(
        `${id}: meterDetail.ts has ${describeEntry(actual)} but the menu card needs ${describeEntry(expected)}. Regenerate src/providers/meterDetail.ts.`,
      );
    }
  }
  for (const id of Object.keys(table)) {
    if (!presentations.has(id)) {
      problems.push(`${id}: meterDetail.ts lists a Provider with no descriptor. Delete it.`);
    }
  }
  return { problems, entries };
}

export function compareUnportableMenuCard(presentations, allowances) {
  const problems = [];
  const used = new Set();
  for (const [id, presentation] of presentations) {
    const allowance = allowances[id] ?? {};
    if (presentation.primaryDetailKind === "requestQuota") {
      if (!allowance.requestQuota) {
        problems.push(
          `${id}: descriptor sets primaryDetailKind .requestQuota. Port it or add UNPORTABLE_MENU_CARD.`,
        );
      } else {
        used.add(`${id}.requestQuota`);
      }
    }
    for (const [field, key] of CLOSURE_FIELDS) {
      if (!presentation[field]) continue;
      if (!allowance[key]) {
        problems.push(`${id}: descriptor sets ${key}. Port it or add UNPORTABLE_MENU_CARD.`);
      } else {
        used.add(`${id}.${key}`);
      }
    }
    for (const key of Object.keys(allowance)) {
      if (!used.has(`${id}.${key}`)) {
        problems.push(`${id}: stale UNPORTABLE_MENU_CARD entry for ${key}. Delete it.`);
      }
    }
  }
  for (const [id, flags] of Object.entries(allowances)) {
    if (presentations.has(id)) continue;
    for (const key of Object.keys(flags)) {
      problems.push(`${id}: stale UNPORTABLE_MENU_CARD entry for ${key}. Delete it.`);
    }
  }
  return problems;
}

export function watchedMenuCardChanges(changedPaths) {
  const hits = [];
  for (const file of changedPaths) {
    for (const watch of MENU_CARD_WATCH_PATHS) {
      if (watch.endsWith("/") ? file.startsWith(watch) : file === watch) {
        hits.push(file);
        break;
      }
    }
  }
  return [...new Set(hits)].sort();
}

export function menuCardReviewProblems(reviewed, candidateSha, changedPaths) {
  const problems = [];
  for (const watch of MENU_CARD_WATCH_PATHS) {
    if (!reviewed.paths.includes(watch)) {
      problems.push(`menuCardReviewed is missing watched path ${watch}.`);
    }
  }
  const candidate = candidateSha.toLowerCase();
  if (reviewed.sha === candidate) return problems;
  const changed = watchedMenuCardChanges(changedPaths);
  if (changed.length === 0) return problems;
  problems.push(
    `Menu card files changed since menuCardReviewed.sha. Set menuCardReviewed.sha to ${candidate} and list: ${changed.join(", ")}.`,
  );
  for (const file of changed) {
    if (!reviewed.paths.includes(file)) {
      problems.push(`menuCardReviewed does not list changed path ${file}.`);
    }
  }
  return problems;
}

export function renderMeterDetail(entries) {
  const ids = Object.keys(entries).sort(compareCatalogId);
  const lines = ids.map((id) => `  ${id}: ${renderEntry(entries[id])},`);
  const body =
    lines.length === 0
      ? "export const METER_DETAIL: Record<string, MeterDetail> = {};\n"
      : `export const METER_DETAIL: Record<string, MeterDetail> = {\n${lines.join("\n")}\n};\n`;
  const type = [
    "export type MeterDetail = {",
    '  primary?: true | "kiroCredits" | "poeBalance";',
    "  secondary?: true;",
    "  primaryReset?: true;",
    "};",
    "",
  ].join("\n");
  return `${METER_DETAIL_BANNER}${type}\n${body}`;
}

export function meterEntriesFromSource(source) {
  const marker = "export const METER_DETAIL";
  const start = source.indexOf(marker);
  if (start < 0) {
    throw new Error("METER_DETAIL is missing");
  }
  const open = source.indexOf("{", start);
  const close = matchCloser(source, open, "{", "}");
  const entries = {};
  for (const part of splitTopLevel(source.slice(open + 1, close), ",")) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const match = /^([A-Za-z0-9]+)\s*:\s*\{([\s\S]*)\}$/.exec(trimmed);
    if (!match) {
      throw new Error(`Could not parse meter detail entry: ${trimmed}`);
    }
    entries[match[1]] = parseEntryBody(match[2]);
  }
  return entries;
}

export async function checkMeterDetailFile(root, entries) {
  const expected = renderMeterDetail(entries);
  const actual = await readFile(path.join(root, METER_DETAIL_PATH), "utf8");
  if (actual === expected) return [];
  return [`${METER_DETAIL_PATH} does not match the menu card descriptors. Regenerate it.`];
}

function renderEntry(entry) {
  const fields = [];
  if (entry.primary === true) fields.push("primary: true");
  else if (entry.primary) fields.push(`primary: "${entry.primary}"`);
  if (entry.secondary) fields.push("secondary: true");
  if (entry.primaryReset) fields.push("primaryReset: true");
  return `{ ${fields.join(", ")} }`;
}

function parseEntryBody(body) {
  const entry = {};
  for (const part of body.split(",")) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const match = /^([A-Za-z0-9]+)\s*:\s*([\s\S]+)$/.exec(trimmed);
    if (!match) {
      throw new Error(`Could not parse meter detail field: ${trimmed}`);
    }
    const key = match[1];
    const raw = match[2].trim();
    if (key === "primary" && raw === "true") entry.primary = true;
    else if (key === "primary" && (raw === '"kiroCredits"' || raw === '"poeBalance"')) entry.primary = JSON.parse(raw);
    else if (key === "secondary" && raw === "true") entry.secondary = true;
    else if (key === "primaryReset" && raw === "true") entry.primaryReset = true;
    else throw new Error(`Unexpected meter detail field ${key}: ${raw}`);
  }
  return entry;
}

function compareCatalogId(left, right) {
  const order = CATALOG_PROVIDER_ORDER;
  const leftIndex = order.indexOf(left);
  const rightIndex = order.indexOf(right);
  const leftRank = leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex;
  const rightRank = rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex;
  if (leftRank !== rightRank) return leftRank - rightRank;
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function sameEntry(expected, actual) {
  return JSON.stringify(normalizeEntry(expected)) === JSON.stringify(normalizeEntry(actual));
}

function normalizeEntry(entry) {
  if (!entry) return {};
  const normalized = {};
  if (entry.primary !== undefined) normalized.primary = entry.primary;
  if (entry.secondary) normalized.secondary = true;
  if (entry.primaryReset) normalized.primaryReset = true;
  return normalized;
}

function describeEntry(entry) {
  const normalized = normalizeEntry(entry);
  const parts = [];
  if (normalized.primary === true) parts.push("primary");
  else if (normalized.primary) parts.push(`primary ${normalized.primary}`);
  if (normalized.secondary) parts.push("secondary");
  if (normalized.primaryReset) parts.push("primaryReset");
  return parts.length === 0 ? "no balance line" : parts.join(", ");
}

function parseArgs(argSource) {
  const args = new Map();
  for (const part of splitTopLevel(argSource, ",")) {
    // Comments sit between arguments. A comma inside one must not split, and the
    // comment itself has to come off before the label or the next argument looks unlabeled.
    const trimmed = stripLeadingTrivia(part);
    if (!trimmed) continue;
    const match = /^([A-Za-z_][A-Za-z0-9_]*)\s*:([\s\S]*)$/.exec(trimmed);
    if (!match) {
      throw new Error(`Unlabeled menu card argument: ${trimmed.slice(0, 80)}`);
    }
    args.set(match[1], match[2].trim());
  }
  return args;
}

function stripLeadingTrivia(source) {
  let index = 0;
  while (index < source.length) {
    if (source.startsWith("//", index) || source.startsWith("/*", index)) {
      index = skipTriviaOrString(source, index);
      continue;
    }
    if (/\s/.test(source[index])) {
      index += 1;
      continue;
    }
    break;
  }
  return source.slice(index).trim();
}

function boolArg(args, name, fallback) {
  if (!args.has(name)) return fallback;
  const raw = stripTrivia(args.get(name));
  if (raw === "true") return true;
  if (raw === "false") return false;
  throw new Error(`${name} is ${raw}, not a boolean literal`);
}

function enumArg(args, name, fallback, allowed) {
  if (!args.has(name)) return fallback;
  const raw = stripTrivia(args.get(name));
  const match = /^\.([A-Za-z0-9_]+)$/.exec(raw);
  if (!match || !allowed.has(match[1])) {
    throw new Error(`${name} is ${raw}, not a supported literal`);
  }
  return match[1];
}

function closureArg(args, name, trivial) {
  if (!args.has(name)) return null;
  const raw = stripLeadingTrivia(args.get(name));
  if (!raw.startsWith("{")) {
    throw new Error(`${name} is not a closure`);
  }
  const normalized = raw.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "").replace(/\s+/g, "");
  return normalized === trivial ? null : raw;
}

function stripTrivia(value) {
  return value.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "").trim();
}

function findCalls(source, name) {
  const calls = [];
  for (let index = 0; index < source.length; index += 1) {
    const skipped = skipTriviaOrString(source, index);
    if (skipped !== index) {
      index = skipped - 1;
      continue;
    }
    if (!source.startsWith(name, index)) continue;
    if (isIdentChar(source[index - 1]) || isIdentChar(source[index + name.length])) continue;
    const open = skipSpaces(source, index + name.length);
    if (source[open] !== "(") continue;
    const end = matchCloser(source, open, "(", ")");
    calls.push(source.slice(open + 1, end));
    index = end;
  }
  return calls;
}

function splitTopLevel(source, separator) {
  const parts = [];
  let start = 0;
  let paren = 0;
  let brace = 0;
  let bracket = 0;
  for (let index = 0; index < source.length; index += 1) {
    const skipped = skipTriviaOrString(source, index);
    if (skipped !== index) {
      index = skipped - 1;
      continue;
    }
    const char = source[index];
    if (char === "(") paren += 1;
    else if (char === ")") paren -= 1;
    else if (char === "{") brace += 1;
    else if (char === "}") brace -= 1;
    else if (char === "[") bracket += 1;
    else if (char === "]") bracket -= 1;
    else if (char === separator && paren === 0 && brace === 0 && bracket === 0) {
      parts.push(source.slice(start, index));
      start = index + 1;
    }
  }
  parts.push(source.slice(start));
  return parts;
}

function matchCloser(source, openIndex, open, close) {
  let depth = 0;
  for (let index = openIndex; index < source.length; index += 1) {
    const skipped = skipTriviaOrString(source, index);
    if (skipped !== index) {
      index = skipped - 1;
      continue;
    }
    if (source[index] === open) depth += 1;
    else if (source[index] === close) {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  throw new Error(`Unterminated ${open}`);
}

function skipSpaces(source, index) {
  let cursor = index;
  while (cursor < source.length) {
    const skipped = skipTriviaOrString(source, cursor);
    if (skipped !== cursor) {
      cursor = skipped;
      continue;
    }
    if (!/\s/.test(source[cursor])) return cursor;
    cursor += 1;
  }
  return cursor;
}

function skipTriviaOrString(source, index) {
  if (source.startsWith("//", index)) {
    const newline = source.indexOf("\n", index);
    return newline < 0 ? source.length : newline + 1;
  }
  if (source.startsWith("/*", index)) {
    const end = source.indexOf("*/", index + 2);
    if (end < 0) throw new Error("Unterminated comment");
    return end + 2;
  }
  if (source.startsWith('"""', index)) {
    const end = source.indexOf('"""', index + 3);
    if (end < 0) throw new Error("Unterminated string");
    return end + 3;
  }
  const quote = source[index];
  if (quote === '"' || quote === "'") return skipString(source, index);
  return index;
}

function skipString(source, index) {
  const quote = source[index];
  let cursor = index + 1;
  while (cursor < source.length) {
    if (source[cursor] === "\\") {
      cursor += 2;
      continue;
    }
    if (source[cursor] === quote) return cursor + 1;
    cursor += 1;
  }
  throw new Error("Unterminated string");
}

function isIdentChar(char) {
  return typeof char === "string" && /[A-Za-z0-9_]/.test(char);
}
